<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
  <ItemGroup>
      <InternalsVisibleTo Include="PersonalDashboard.Tests" />
      <ProjectReference Include="KnowledgeBase.Api\KnowledgeBase.Api.csproj" />
      <Compile Remove="tests/**" />
      <Compile Remove="KnowledgeBase.Api/**" />
      <Content Remove="tests/**" />
      <EmbeddedResource Remove="tests/**" />
      <None Remove="tests/**" />
    </ItemGroup>
</Project>
